name: GPT Translate per Commit
 
on:
  push:
    branches:
      - main
jobs:
  gpt_translate:
    runs-on: ubuntu-latest
 
    steps:
      - name: Run GPT Translate
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          #inputFiles: ${{ steps.changed_files.outputs.files }}
          inputFiles: '*.md'
          outputFiles: 'DE/**/*.md FR/**/*.md'
          languages: 'German French'