- name: GPT Translate
  # You may pin to the exact commit or the version.
  # uses: 3ru/gpt-translate@b8ddfab17c3ad47b59ebe1906724dddfe460c304
  uses: 3ru/gpt-translate@v1.2.0-beta
  with:
    # GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)
    token: # optional, default is ${{ github.token }}
    # API Key
    apikey: 
    # AI Provider
    provider: # optional, default is openai
    # The language model to use.
    model: # optional, default is gpt-4o
    # The input prompt to generate the text from
    prompt: # optional, default is Please translate the given text into naturalistic {targetLanguage}.
    # The system prompt to use that specifies the behavior of the model
    systemPrompt: # optional
    # Replace the base path of openai api
    basePath: # optional
    # Input files to translate
    inputFiles: # optional
    # Output files to save
    outputFiles: # optional
    # Language to translate to
    languages: # optional
    # Controls diversity via nucleus sampling (0 to 1)
    top_p: # optional, default is 0.5
    # Controls randomness of the output (0 to 2)
    temperature: # optional, default is 0.3
    # Maximum number of tokens in the chat completion
    max_tokens: # optional
    # Penalizes new tokens based on their existing presence (-2 to 2)
    presence_penalty: # optional, default is 0
    # Penalizes new tokens based on their frequency (-2 to 2)
    frequency_penalty: # optional, default is 0
    # Seed value for deterministic sampling
    seed: # optional
          
